### ISSUE TITLE
Another extension with same functionality

### ISSUE THREAD

**Issue by Venryx** [chrisyuska/simpl#2]
Just thought I'd mention that there is another Chrome extension here on Github which has the same functionality as this one: https://github.com/eden-lane/ImagePlus

Not sure which is better, or whether it's worth merging, just thought I'd let you know. (with some fixes, I've gotten both extensions to work)

**Comment by chrisyuska** [comment]
Thanks for the info.  I don't have much time to maintain or work on this extension right now, but would like to polish it up at some point.  It's kind of surprising it still works on Chrome at all after a couple years with no changes.
